apiVersion: v1
kind: ServiceAccount
metadata:
  name: in-use-protector
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: in-use-protector-runner
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: in-use-protector-role
subjects:
  - kind: ServiceAccount
    name: in-use-protector
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: in-use-protector-runner
  apiGroup: rbac.authorization.k8s.io
